language: node_js
node_js: stable
branches:
  only:
    - source
cache:
  apt: true
  yarn: true
  directories:
    - node_modules
addons:
  ssh_known_hosts: 47.106.174.43
before_install:
  - openssl aes-256-cbc -K $encrypted_1db4be9f9453_key -iv $encrypted_1db4be9f9453_iv
    -in deploy_rsa.enc -out deploy_rsa -d
  - eval $(ssh-agent -s)
  - chmod 600 deploy_rsa
  - ssh-add deploy_rsa
  - git config --global user.name "xiaofeizao1996"
  - git config --global user.email "xiaofeizao1996@gmail.com"
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - npm install -g hexo-cli
install:
  - yarn
script:
  - hexo clean
  - hexo generate
after_success:
  - cd ./public
  - git init
  - git add --all .
  - git commit -m "Travis CI Auto Builder"
  - git push --quiet --force https://$REPO_TOKEN@github.com/xiaofeizao1996/xiaofeizao1996.github.io.git
    master
  - scp -o stricthostkeychecking=no  -r * root@47.106.174.43:/home/public
